<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get categories
        $sofas = Category::where('slug', 'sofas')->first();
        $chairs = Category::where('slug', 'chairs')->first();
        $tables = Category::where('slug', 'tables')->first();
        $beds = Category::where('slug', 'beds')->first();
        $storage = Category::where('slug', 'storage')->first();
        $lighting = Category::where('slug', 'lighting')->first();
        $decor = Category::where('slug', 'decor')->first();

        // Furniture products
        $products = [
            [
                'name' => 'Cloud Comfort Sofa',
                'slug' => 'cloud-comfort-sofa',
                'sku' => 'SOF-CLD-001',
                'description' => 'Experience ultimate relaxation with our Cloud Comfort Sofa. Featuring plush cushioning and premium upholstery, this sofa is designed for maximum comfort while adding elegance to your living space.',
                'short_description' => 'Premium plush sofa with cloud-like comfort',
                'price' => 89990.00,
                'sale_price' => 74990.00,
                'stock_quantity' => 15,
                'low_stock_threshold' => 3,
                'category_id' => $sofas?->id,
                'status' => 'active',
                'is_featured' => true,
                'is_new' => true,
                'published_at' => now(),
                'image' => '/images/products/cloudsofa.png',
            ],
            [
                'name' => 'Velvet Lounge Sofa',
                'slug' => 'velvet-lounge-sofa',
                'sku' => 'SOF-VLV-002',
                'description' => 'A statement piece in rich velvet fabric. The Velvet Lounge Sofa combines mid-century modern design with contemporary comfort.',
                'short_description' => 'Luxurious velvet sofa with elegant design',
                'price' => 125000.00,
                'sale_price' => null,
                'stock_quantity' => 8,
                'low_stock_threshold' => 2,
                'category_id' => $sofas?->id,
                'status' => 'active',
                'is_featured' => true,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/velvetlounge.png',
            ],
            [
                'name' => 'Velvet Accent Armchair',
                'slug' => 'velvet-accent-armchair',
                'sku' => 'CHR-VLV-001',
                'description' => 'Add a touch of sophistication with this plush velvet armchair. Perfect for reading corners or as an accent piece in any room.',
                'short_description' => 'Elegant velvet armchair for any space',
                'price' => 34990.00,
                'sale_price' => 29990.00,
                'stock_quantity' => 25,
                'low_stock_threshold' => 5,
                'category_id' => $chairs?->id,
                'status' => 'active',
                'is_featured' => true,
                'is_new' => true,
                'published_at' => now(),
                'image' => '/images/products/velvetarmchair.png',
            ],
            [
                'name' => 'Marble Dining Table',
                'slug' => 'marble-dining-table',
                'sku' => 'TBL-MRB-001',
                'description' => 'Elevate your dining experience with our stunning marble dining table. Features genuine marble top with a sleek metal base.',
                'short_description' => 'Elegant marble-top dining table',
                'price' => 149990.00,
                'sale_price' => null,
                'stock_quantity' => 5,
                'low_stock_threshold' => 2,
                'category_id' => $tables?->id,
                'status' => 'active',
                'is_featured' => true,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/marbledining.png',
            ],
            [
                'name' => 'Minimalist Coffee Table',
                'slug' => 'minimalist-coffee-table',
                'sku' => 'TBL-MIN-001',
                'description' => 'Clean lines and functional design make this coffee table a perfect addition to modern living spaces.',
                'short_description' => 'Modern minimalist coffee table',
                'price' => 24990.00,
                'sale_price' => 19990.00,
                'stock_quantity' => 30,
                'low_stock_threshold' => 5,
                'category_id' => $tables?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => true,
                'published_at' => now(),
                'image' => '/images/products/minimalisttable.png',
            ],
            [
                'name' => 'Marble Side Table',
                'slug' => 'marble-side-table',
                'sku' => 'TBL-MRB-002',
                'description' => 'A compact yet elegant side table with a marble top and gold-finished metal legs.',
                'short_description' => 'Compact marble side table',
                'price' => 18990.00,
                'sale_price' => null,
                'stock_quantity' => 20,
                'low_stock_threshold' => 5,
                'category_id' => $tables?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/marbletable.png',
            ],
            [
                'name' => 'Royal Bed Frame',
                'slug' => 'royal-bed-frame',
                'sku' => 'BED-RYL-001',
                'description' => 'Transform your bedroom into a sanctuary with our Royal Bed Frame. Features tufted upholstered headboard and solid wood construction.',
                'short_description' => 'Luxurious upholstered bed frame',
                'price' => 189990.00,
                'sale_price' => 159990.00,
                'stock_quantity' => 6,
                'low_stock_threshold' => 2,
                'category_id' => $beds?->id,
                'status' => 'active',
                'is_featured' => true,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/royalbedframe.png',
            ],
            [
                'name' => 'Modern Sideboard',
                'slug' => 'modern-sideboard',
                'sku' => 'STR-SDB-001',
                'description' => 'Stylish storage solution with ample space for your dining essentials. Features clean lines and durable construction.',
                'short_description' => 'Contemporary storage sideboard',
                'price' => 69990.00,
                'sale_price' => null,
                'stock_quantity' => 12,
                'low_stock_threshold' => 3,
                'category_id' => $storage?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => true,
                'published_at' => now(),
                'image' => '/images/products/sideboard.png',
            ],
            [
                'name' => 'Walnut Media Console',
                'slug' => 'walnut-media-console',
                'sku' => 'STR-SDB-002',
                'description' => 'Beautiful walnut wood media console with integrated cable management and adjustable shelving.',
                'short_description' => 'Walnut media console unit',
                'price' => 79990.00,
                'sale_price' => 69990.00,
                'stock_quantity' => 8,
                'low_stock_threshold' => 2,
                'category_id' => $storage?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/sideboard1.png',
            ],
            [
                'name' => 'Scandinavian Bookshelf',
                'slug' => 'scandinavian-bookshelf',
                'sku' => 'STR-SDB-003',
                'description' => 'Minimalist Scandinavian-inspired bookshelf with open shelving and natural wood finish.',
                'short_description' => 'Nordic-style bookshelf',
                'price' => 44990.00,
                'sale_price' => null,
                'stock_quantity' => 15,
                'low_stock_threshold' => 3,
                'category_id' => $storage?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/sideboard2.png',
            ],
            [
                'name' => 'Crystal Chandelier',
                'slug' => 'crystal-chandelier',
                'sku' => 'LGT-CHN-001',
                'description' => 'Make a statement with our stunning crystal chandelier. Perfect for dining rooms, entryways, or living spaces.',
                'short_description' => 'Elegant crystal chandelier',
                'price' => 89990.00,
                'sale_price' => null,
                'stock_quantity' => 4,
                'low_stock_threshold' => 2,
                'category_id' => $lighting?->id,
                'status' => 'active',
                'is_featured' => true,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/chandelier.png',
            ],
            [
                'name' => 'Modern Pendant Light',
                'slug' => 'modern-pendant-light',
                'sku' => 'LGT-CHN-002',
                'description' => 'Sleek modern pendant light with adjustable height. Ideal for kitchen islands and dining areas.',
                'short_description' => 'Contemporary pendant lighting',
                'price' => 24990.00,
                'sale_price' => 19990.00,
                'stock_quantity' => 20,
                'low_stock_threshold' => 5,
                'category_id' => $lighting?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => true,
                'published_at' => now(),
                'image' => '/images/products/chandelier1.png',
            ],
            [
                'name' => 'Artisan Table Lamp',
                'slug' => 'artisan-table-lamp',
                'sku' => 'LGT-TBL-001',
                'description' => 'Handcrafted table lamp with unique artisan design. Creates warm ambient lighting for any space.',
                'short_description' => 'Handcrafted artisan lamp',
                'price' => 14990.00,
                'sale_price' => null,
                'stock_quantity' => 35,
                'low_stock_threshold' => 8,
                'category_id' => $lighting?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/artisanlamp.png',
            ],
            [
                'name' => 'Modern Table Lamp',
                'slug' => 'modern-table-lamp',
                'sku' => 'LGT-TBL-002',
                'description' => 'Sleek modern table lamp with brushed metal base and fabric shade.',
                'short_description' => 'Contemporary table lamp',
                'price' => 12990.00,
                'sale_price' => 9990.00,
                'stock_quantity' => 40,
                'low_stock_threshold' => 10,
                'category_id' => $lighting?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/tablelamp.png',
            ],
            [
                'name' => 'Ceramic Art Vase',
                'slug' => 'ceramic-art-vase',
                'sku' => 'DCR-VAS-001',
                'description' => 'Beautiful ceramic vase with artistic glazed finish. Perfect for fresh flowers or as a standalone decorative piece.',
                'short_description' => 'Decorative ceramic vase',
                'price' => 4990.00,
                'sale_price' => 3990.00,
                'stock_quantity' => 50,
                'low_stock_threshold' => 10,
                'category_id' => $decor?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => true,
                'published_at' => now(),
                'image' => '/images/products/ceramicvase.png',
            ],
            [
                'name' => 'Luxury Throw Pillow',
                'slug' => 'luxury-throw-pillow',
                'sku' => 'DCR-PLW-001',
                'description' => 'Premium throw pillow with soft velvet cover and plush filling. Available in multiple colors.',
                'short_description' => 'Velvet decorative pillow',
                'price' => 2490.00,
                'sale_price' => null,
                'stock_quantity' => 100,
                'low_stock_threshold' => 20,
                'category_id' => $decor?->id,
                'status' => 'active',
                'is_featured' => false,
                'is_new' => false,
                'published_at' => now(),
                'image' => '/images/products/pillow.png',
            ],
        ];

        foreach ($products as $productData) {
            $image = $productData['image'];
            unset($productData['image']);

            $product = Product::create($productData);

            // Create product image
            if ($image) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_path' => $image,
                    'alt_text' => $product->name,
                    'is_primary' => true,
                    'display_order' => 0,
                ]);
            }
        }
    }
}
